### ISSUE TITLE
SpaceEZ?

### ISSUE THREAD

**Issue by mcdoug62** [ntwrkguru/junos-automation-vm#1]
Any plans to update the VM to include the SpaceEZ Python library ?
It recently went to v1.0.0 on git hub at https://github.com/Juniper/py-space-platform 

Thanks for putting this VM together, BTW.

/doug

**Comment by ntwrkguru** [comment]
Yes. It's on my to do list.

**Comment by ntwrkguru** [comment]
This was added in the the 2015.04.17 release. Try it out and let me know!
